import type { Domain } from '../types/assessment.types.js';

export const DOMAINS: Domain[] = [
  // ─── Domain 1: Governance & Democracy ───
  {
    key: 'governance',
    name: 'Governance & Democracy',
    shortName: 'Governance',
    description: 'Democratic decision-making structures, organisational autonomy, stakeholder participation, and transparent governance aligned with EMES indicators and the EU social economy framework.',
    icon: 'BuildingLibraryIcon',
    color: '#6366F1', // indigo
    questions: [
      {
        id: 'gov-q1',
        i18nKey: 'domains.governance.questions.q1.text',
        domainKey: 'governance',
        text: 'How would you rate the overall maturity of your governance structures and democratic decision-making processes, as reflected in the EMES indicators for social enterprise?',
        type: 'maturity',
        description: 'Consider board composition, meeting frequency, decision-making protocols, and stakeholder representation. The EMES Network identifies democratic control (not based on capital ownership), organisational autonomy, and a participatory nature as core governance indicators for social enterprises. The Council Recommendation on Social Economy Framework Conditions (2023) also emphasises transparent and accountable governance.',
        required: true,
        weight: 1.5,
        tags: ['governance-structure', 'democracy'],
      },
      {
        id: 'gov-q2',
        i18nKey: 'domains.governance.questions.q2.text',
        domainKey: 'governance',
        text: 'To what extent are participants (workers/trainees) involved in organisational decision-making, reflecting the EMES participatory governance principle?',
        type: 'likert',
        description: '1 = No involvement, 5 = Full co-governance with voting rights. The EMES framework emphasises that social enterprises involve various stakeholders affected by the activity in their governance. The EU Council Recommendation (2023) calls on Member States to promote participatory governance models within the social economy.',
        required: true,
        weight: 1.0,
        tags: ['participation', 'democracy'],
      },
      {
        id: 'gov-q3',
        i18nKey: 'domains.governance.questions.q3.text',
        domainKey: 'governance',
        text: 'Describe how your board or governing body is composed. What stakeholder groups are represented, and how does this reflect the EMES principle of democratic control?',
        type: 'narrative',
        description: 'Include details about participant representation, community members, independent directors, and how diverse perspectives are ensured. The EU social economy framework values governance that is not based on capital ownership but on democratic participation. Reference the Council Recommendation on Social Economy Framework Conditions (2023), which encourages Member States to establish clear legal frameworks supporting multi-stakeholder governance.',
        required: true,
        weight: 0,
        placeholder: 'Describe your board composition, stakeholder representation, and alignment with democratic governance principles...',
        tags: ['board-composition', 'diversity'],
      },
      {
        id: 'gov-q4',
        i18nKey: 'domains.governance.questions.q4.text',
        domainKey: 'governance',
        text: 'What mechanisms exist for transparency and accountability in your organisation, consistent with EU social economy standards?',
        type: 'narrative',
        description: 'Consider annual reports, financial transparency, stakeholder reporting, grievance procedures, and public accountability measures. The EMES autonomy indicator requires independence from public authorities while maintaining accountability. The EU Social Economy Action Plan (2021) stresses that social enterprises should adopt transparent reporting practices to build trust and demonstrate their social value.',
        required: true,
        weight: 0,
        placeholder: 'Describe your transparency and accountability mechanisms, including any alignment with EU social economy reporting expectations...',
        tags: ['transparency', 'accountability'],
      },
      {
        id: 'gov-q5',
        i18nKey: 'domains.governance.questions.q5.text',
        domainKey: 'governance',
        text: 'Provide an example of a significant decision where multiple stakeholder perspectives were actively sought and incorporated, demonstrating participatory governance in practice.',
        type: 'narrative',
        description: 'This could be a strategic decision, policy change, or operational matter where inclusive consultation was practiced. The EMES participatory dimension highlights that decision-making power should not rest solely on capital ownership but should involve workers, users, and community representatives — a principle reinforced in the 2023 Council Recommendation.',
        required: false,
        weight: 0,
        placeholder: 'Share a specific example of inclusive decision-making that reflects participatory governance...',
        tags: ['participation', 'evidence'],
      },
    ],
  },

  // ─── Domain 2: Social Mission & Impact ───
  {
    key: 'social-mission',
    name: 'Social Mission & Impact',
    shortName: 'Social Mission',
    description: 'Clarity of social mission focused on helping people at risk of permanent labour market exclusion through productive activity, alignment with the European Pillar of Social Rights, and contribution to UN SDGs.',
    icon: 'HeartIcon',
    color: '#EC4899', // pink
    questions: [
      {
        id: 'sm-q1',
        i18nKey: 'domains.socialMission.questions.q1.text',
        domainKey: 'social-mission',
        text: 'How would you rate the maturity of your social mission definition, integration, and impact measurement in line with the EU definition of WISEs?',
        type: 'maturity',
        description: 'Consider how clearly your mission is defined, how well it is embedded in operations, and whether you can demonstrate impact. The EU defines WISEs as organisations whose main objective is the professional integration of people who experience severe difficulties in the labour market, through productive activity. ENSIE (European Network of Social Integration Enterprises) promotes standardised impact measurement for WISEs across Europe.',
        required: true,
        weight: 1.5,
        tags: ['mission-clarity', 'impact'],
      },
      {
        id: 'sm-q2',
        i18nKey: 'domains.socialMission.questions.q2.text',
        domainKey: 'social-mission',
        text: 'To what extent does your organisation prioritise social outcomes — particularly labour market integration for disadvantaged groups — alongside financial sustainability?',
        type: 'likert',
        description: '1 = Financial outcomes dominate, 5 = Social mission (labour market integration for excluded populations) is the primary driver of all decisions. The European Pillar of Social Rights (Principle 4: Active support to employment) affirms the right to timely and tailor-made assistance to improve employment prospects. WISEs are recognised as key instruments for delivering on this principle.',
        required: true,
        weight: 1.0,
        tags: ['mission-priority', 'social-outcomes'],
      },
      {
        id: 'sm-q3',
        i18nKey: 'domains.socialMission.questions.q3.text',
        domainKey: 'social-mission',
        text: 'Describe your organisation\'s social mission and the specific populations or communities you serve, with reference to their risk of permanent labour market exclusion.',
        type: 'narrative',
        description: 'Include the target groups, geographic focus, types of disadvantage addressed, and how you define your beneficiaries. The EU recognises WISEs as serving people at risk of permanent exclusion from the labour market — including long-term unemployed, people with disabilities, migrants and refugees, ex-offenders, and other vulnerable groups. Align your description with the European Pillar of Social Rights and relevant UN SDGs (SDG 1: No Poverty, SDG 8: Decent Work, SDG 10: Reduced Inequalities).',
        required: true,
        weight: 0,
        placeholder: 'Describe your social mission, target populations at risk of labour market exclusion, and alignment with EU social objectives and UN SDGs...',
        tags: ['mission-statement', 'target-population'],
      },
      {
        id: 'sm-q4',
        i18nKey: 'domains.socialMission.questions.q4.text',
        domainKey: 'social-mission',
        text: 'What social outcomes have you achieved in the past 12 months? Provide specific evidence, drawing on ENSIE-aligned impact indicators where possible.',
        type: 'narrative',
        description: 'Include quantitative data (e.g., number of people supported, employment integration rates, qualification attainment) and qualitative evidence (stories of change, testimonials). ENSIE\'s Impact-WISEs framework provides guidance on comparable outcome indicators across European WISEs. Consider outcomes aligned with the European Pillar of Social Rights and SDG targets.',
        required: true,
        weight: 0,
        placeholder: 'Describe your social outcomes with evidence, referencing ENSIE impact indicators and EU social policy objectives...',
        tags: ['outcomes', 'evidence'],
      },
      {
        id: 'sm-q5',
        i18nKey: 'domains.socialMission.questions.q5.text',
        domainKey: 'social-mission',
        text: 'How does your organisation contribute to the broader community beyond your direct participants, including alignment with EU social cohesion goals?',
        type: 'narrative',
        description: 'Consider community economic impact, social cohesion, environmental benefits, advocacy, and sector development. The EU Social Economy Action Plan (2021) recognises social enterprises as contributors to inclusive growth and territorial cohesion. Describe contributions relevant to SDG 11 (Sustainable Cities and Communities) and the European Pillar of Social Rights\' collective provisions.',
        required: false,
        weight: 0,
        placeholder: 'Describe your broader community impact and alignment with EU social cohesion objectives...',
        tags: ['community-benefit', 'wider-impact'],
      },
    ],
  },

  // ─── Domain 3: Employment Pathways ───
  {
    key: 'employment',
    name: 'Employment Pathways',
    shortName: 'Employment',
    description: 'Quality of supported and transitional employment, social insertion pathways, professional reintegration, career progression, and skill development — reflecting EU employment integration models.',
    icon: 'BriefcaseIcon',
    color: '#F59E0B', // amber
    questions: [
      {
        id: 'emp-q1',
        i18nKey: 'domains.employment.questions.q1.text',
        domainKey: 'employment',
        text: 'How would you rate the maturity of your employment pathways — including supported employment, transitional employment, and professional reintegration support systems?',
        type: 'maturity',
        description: 'Consider the quality of employment offered, progression opportunities, skill development, and transition to open employment. EU employment integration models include France\'s SIAE (Structures d\'Insertion par l\'Activité Économique), Spain\'s Empresas de Inserción and Centros Especiales de Empleo, and Italy\'s Cooperativa Sociale Type B. ESF+ funded programmes across Member States support these social insertion pathways.',
        required: true,
        weight: 1.5,
        tags: ['employment-quality', 'pathways'],
      },
      {
        id: 'emp-q2',
        i18nKey: 'domains.employment.questions.q2.text',
        domainKey: 'employment',
        text: 'To what extent does your organisation provide structured skill development and accredited training aligned with recognised qualification frameworks?',
        type: 'likert',
        description: '1 = No formal training, 5 = Comprehensive accredited training with individual development plans aligned to EQF (European Qualifications Framework). ESF+ funded programmes emphasise the importance of accredited, transferable skills development within social insertion pathways.',
        required: true,
        weight: 1.0,
        tags: ['training', 'skill-development'],
      },
      {
        id: 'emp-q3',
        i18nKey: 'domains.employment.questions.q3.text',
        domainKey: 'employment',
        text: 'Describe the employment or social insertion model your organisation uses, including elements of supported employment, transitional employment, or professional reintegration.',
        type: 'narrative',
        description: 'Include job types, working conditions, pay levels, contract types, progression stages, and how you prepare people for open-market employment. Reference comparable EU models where relevant: France\'s SIAE provides transitional employment through chantiers d\'insertion and entreprises d\'insertion; Spain\'s Empresas de Inserción offer personalised integration itineraries; Italy\'s Cooperativa Sociale Type B integrates disadvantaged workers directly into productive cooperatives. Describe where your model sits on the continuum from sheltered employment to full open-market integration.',
        required: true,
        weight: 0,
        placeholder: 'Describe your social insertion / employment integration model, referencing EU approaches such as supported employment, transitional employment, or professional reintegration...',
        tags: ['employment-model', 'job-quality'],
      },
      {
        id: 'emp-q4',
        i18nKey: 'domains.employment.questions.q4.text',
        domainKey: 'employment',
        text: 'What transition outcomes have your participants achieved? Include data on professional reintegration and employment retention where available.',
        type: 'narrative',
        description: 'Share transition rates into open-market employment, employment retention at 6/12 months, types of employment secured, and factors contributing to successful social insertion. ENSIE data shows that across European WISEs, transition-to-work rates vary by model but are a key indicator of WISE effectiveness. ESF+ programme evaluations also track these professional reintegration outcomes.',
        required: true,
        weight: 0,
        placeholder: 'Describe professional reintegration outcomes, transition rates, and employment retention data...',
        tags: ['transition-outcomes', 'retention'],
      },
      {
        id: 'emp-q5',
        i18nKey: 'domains.employment.questions.q5.text',
        domainKey: 'employment',
        text: 'Share an example of a participant\'s social insertion journey through your organisation, illustrating the pathway from exclusion to integration.',
        type: 'narrative',
        description: 'Describe the pathway from entry to professional reintegration or stable supported employment, including challenges overcome and accompaniment provided (anonymise personal details). EU social insertion models emphasise individualised integration itineraries — describe how your approach reflects this principle.',
        required: false,
        weight: 0,
        placeholder: 'Share an anonymised participant social insertion journey, illustrating the pathway from exclusion toward integration...',
        tags: ['case-study', 'evidence'],
      },
    ],
  },

  // ─── Domain 4: Organisational Culture ───
  {
    key: 'culture',
    name: 'Organisational Culture',
    shortName: 'Culture',
    description: 'Inclusion values grounded in the European Charter of Fundamental Rights, participant agency and voice, dignity, trauma-informed practice, and staff capacity.',
    icon: 'UserGroupIcon',
    color: '#8B5CF6', // violet
    questions: [
      {
        id: 'cul-q1',
        i18nKey: 'domains.culture.questions.q1.text',
        domainKey: 'culture',
        text: 'How would you rate the maturity of your organisational culture in terms of inclusion, dignity, and participant agency — reflecting the values of the European Charter of Fundamental Rights?',
        type: 'maturity',
        description: 'Consider how embedded values of inclusion are, whether participants have genuine voice and agency, and the overall workplace culture. The European Charter of Fundamental Rights enshrines human dignity (Article 1), non-discrimination (Article 21), and the integration of persons with disabilities (Article 26). European social work traditions increasingly emphasise trauma-informed practice as essential to working with people facing complex disadvantage.',
        required: true,
        weight: 1.5,
        tags: ['inclusion', 'agency'],
      },
      {
        id: 'cul-q2',
        i18nKey: 'domains.culture.questions.q2.text',
        domainKey: 'culture',
        text: 'To what extent do participants have genuine voice and influence over their own work experience and support, consistent with EU rights-based approaches?',
        type: 'likert',
        description: '1 = No formal input mechanisms, 5 = Participants co-design their work experience and support. The European Charter of Fundamental Rights (Article 15: Freedom to choose an occupation) and the European Pillar of Social Rights (Principle 3: Equal opportunities) underpin the right of all persons to meaningful participation in decisions affecting their working life.',
        required: true,
        weight: 1.0,
        tags: ['voice', 'participation'],
      },
      {
        id: 'cul-q3',
        i18nKey: 'domains.culture.questions.q3.text',
        domainKey: 'culture',
        text: 'Describe how your organisation promotes dignity, respect, and non-discrimination in daily operations, aligned with the European Charter of Fundamental Rights.',
        type: 'narrative',
        description: 'Include policies, practices, physical environment, language used, and how you address discrimination or exclusion. Reference the Charter\'s provisions on human dignity (Article 1), non-discrimination (Article 21), and equality between women and men (Article 23). European social work traditions emphasise trauma-informed approaches — describe how your practice recognises the impact of adverse experiences on participants and adapts accordingly.',
        required: true,
        weight: 0,
        placeholder: 'Describe your approach to dignity, non-discrimination, and trauma-informed practice, referencing European rights frameworks...',
        tags: ['dignity', 'inclusion-practice'],
      },
      {
        id: 'cul-q4',
        i18nKey: 'domains.culture.questions.q4.text',
        domainKey: 'culture',
        text: 'How do you invest in staff capacity and wellbeing to sustain a trauma-informed, rights-based organisational culture?',
        type: 'narrative',
        description: 'Include staff training (particularly in trauma-informed practice and rights-based approaches), supervision, professional development, workload management, and wellbeing support. European frameworks recognise that frontline staff in WISEs require ongoing professional development to maintain the quality of accompaniment and support provided to participants facing complex barriers.',
        required: true,
        weight: 0,
        placeholder: 'Describe staff development, trauma-informed training, and wellbeing support...',
        tags: ['staff-capacity', 'wellbeing'],
      },
      {
        id: 'cul-q5',
        i18nKey: 'domains.culture.questions.q5.text',
        domainKey: 'culture',
        text: 'Provide an example of how participant feedback has led to a meaningful change in your organisation, demonstrating genuine voice and agency.',
        type: 'narrative',
        description: 'Describe a specific instance where participant voice directly influenced policy, practice, or organisational development. The EU rights-based approach and European social work tradition of participatory practice both emphasise that service users should be active agents in shaping the services they receive — not passive recipients.',
        required: false,
        weight: 0,
        placeholder: 'Share an example of participant-led change that demonstrates genuine voice and agency...',
        tags: ['feedback', 'evidence'],
      },
    ],
  },

  // ─── Domain 5: Economic Sustainability ───
  {
    key: 'economic',
    name: 'Economic Sustainability',
    shortName: 'Economic',
    description: 'Revenue diversification, commercial viability, financial planning, and the balance between earned revenue, public contracts, and subsidies — informed by EU state aid rules, social procurement directives, and ESF+ funding.',
    icon: 'CurrencyEuroIcon',
    color: '#10B981', // emerald
    questions: [
      {
        id: 'eco-q1',
        i18nKey: 'domains.economic.questions.q1.text',
        domainKey: 'economic',
        text: 'How would you rate the maturity of your financial sustainability and economic model within the EU social enterprise landscape?',
        type: 'maturity',
        description: 'Consider revenue diversification, financial planning, commercial revenue proportion, and long-term viability. ENSIE data shows that European WISEs typically derive revenue from multiple sources: approximately 42.8% from public authorities (contracts and subsidies), 37.6% from enterprises (B2B commercial activity), and 19.6% from private clients. EU state aid rules for WISEs and social procurement under Directive 2014/24/EU shape the operating environment.',
        required: true,
        weight: 1.5,
        tags: ['financial-sustainability', 'viability'],
      },
      {
        id: 'eco-q2',
        i18nKey: 'domains.economic.questions.q2.text',
        domainKey: 'economic',
        text: 'What proportion of your revenue comes from commercial trading (as opposed to grants, public subsidies, or ESF+ programme funding)?',
        type: 'likert',
        description: '1 = <20% commercial revenue, 2 = 20-40%, 3 = 40-60%, 4 = 60-80%, 5 = >80% commercial revenue. ENSIE data indicates European WISEs average roughly 57% of revenue from market-based sources (enterprises and private clients combined), with 43% from public authorities. The balance varies significantly by national context and WISE model.',
        required: true,
        weight: 1.0,
        tags: ['revenue-mix', 'commercial-income'],
      },
      {
        id: 'eco-q3',
        i18nKey: 'domains.economic.questions.q3.text',
        domainKey: 'economic',
        text: 'Describe your organisation\'s revenue model and how you balance commercial activity with social mission, referencing relevant EU funding and procurement frameworks.',
        type: 'narrative',
        description: 'Include revenue streams, pricing strategy, how commercial decisions are guided by mission, and any tensions you navigate. Consider how EU instruments shape your model: social procurement (Directive 2014/24/EU allows reserved contracts for WISEs under Article 20), ESF+ programme funding for employment integration, InvestEU social window for investment capital, and national WISE subsidy schemes implementing EU state aid rules.',
        required: true,
        weight: 0,
        placeholder: 'Describe your revenue model, mission-commerce balance, and use of EU funding and procurement frameworks...',
        tags: ['revenue-model', 'mission-balance'],
      },
      {
        id: 'eco-q4',
        i18nKey: 'domains.economic.questions.q4.text',
        domainKey: 'economic',
        text: 'What financial planning and risk management practices do you have in place to ensure long-term economic sustainability?',
        type: 'narrative',
        description: 'Include budgeting processes, reserves policy, scenario planning, and how you manage financial risks. Consider risks specific to WISEs in the EU context: dependency on public procurement cycles, changes in ESF+ programming periods, EU state aid compliance requirements, and the challenge of maintaining competitiveness while fulfilling social insertion objectives.',
        required: true,
        weight: 0,
        placeholder: 'Describe your financial planning, risk management, and strategies for navigating EU funding cycles...',
        tags: ['financial-planning', 'risk-management'],
      },
      {
        id: 'eco-q5',
        i18nKey: 'domains.economic.questions.q5.text',
        domainKey: 'economic',
        text: 'How has your financial model evolved over time, and what are your plans for future sustainability within the evolving EU social economy landscape?',
        type: 'narrative',
        description: 'Share your financial journey, lessons learned, and strategic plans for long-term economic sustainability. Consider the opportunities presented by the EU Social Economy Action Plan (2021), the growing social procurement market under Directive 2014/24/EU, the InvestEU social window, and the increasing recognition of WISEs in EU structural funds programming.',
        required: false,
        weight: 0,
        placeholder: 'Describe your financial evolution and future plans within the EU social economy context...',
        tags: ['financial-evolution', 'strategy'],
      },
    ],
  },

  // ─── Domain 6: Stakeholder Engagement ───
  {
    key: 'stakeholders',
    name: 'Stakeholder Engagement',
    shortName: 'Stakeholders',
    description: 'Employer partnerships, community connections, government relationships, and engagement with European WISE networks including ENSIE, RREUSE, CECOP-CICOPA, and the Euclid Network.',
    icon: 'HandshakeIcon',
    color: '#0EA5E9', // sky
    questions: [
      {
        id: 'stk-q1',
        i18nKey: 'domains.stakeholders.questions.q1.text',
        domainKey: 'stakeholders',
        text: 'How would you rate the maturity of your stakeholder engagement and partnership development, including engagement with EU-level WISE networks?',
        type: 'maturity',
        description: 'Consider the breadth and depth of your external relationships, including employers, community, government, and sector networks. Key European networks for WISEs include ENSIE (European Network of Social Integration Enterprises), RREUSE (for reuse and recycling social enterprises), CECOP-CICOPA (for cooperatives), and the Euclid Network. The EU Social Economy Gateway serves as a central resource for connecting with these ecosystems.',
        required: true,
        weight: 1.5,
        tags: ['partnerships', 'engagement'],
      },
      {
        id: 'stk-q2',
        i18nKey: 'domains.stakeholders.questions.q2.text',
        domainKey: 'stakeholders',
        text: 'How effectively does your organisation engage with employers for participant placement, social insertion, and sustained employment integration?',
        type: 'likert',
        description: '1 = No employer engagement, 5 = Deep, ongoing partnerships with multiple employers including co-design of roles and sustained post-placement support. European WISEs increasingly develop employer engagement strategies that go beyond placement to include awareness-raising about inclusive hiring and ongoing accompaniment during integration.',
        required: true,
        weight: 1.0,
        tags: ['employer-engagement', 'placement'],
      },
      {
        id: 'stk-q3',
        i18nKey: 'domains.stakeholders.questions.q3.text',
        domainKey: 'stakeholders',
        text: 'Describe your key external partnerships and how they support your social insertion mission, including any EU-funded collaborative projects.',
        type: 'narrative',
        description: 'Include employer partners, community organisations, government agencies, funders, and how these relationships are maintained. Consider participation in EU-funded projects such as Horizon Europe, Erasmus+ KA2 (cooperation partnerships), or ESF+ transnational cooperation. The EU Social Economy Gateway provides resources for identifying partnership opportunities across Member States.',
        required: true,
        weight: 0,
        placeholder: 'Describe your key partnerships, EU network memberships, and participation in EU-funded collaborative projects...',
        tags: ['partnerships', 'network'],
      },
      {
        id: 'stk-q4',
        i18nKey: 'domains.stakeholders.questions.q4.text',
        domainKey: 'stakeholders',
        text: 'How do you engage with and contribute to the broader European WISE and social enterprise sector?',
        type: 'narrative',
        description: 'Include engagement with sector networks (ENSIE, RREUSE, CECOP-CICOPA, Euclid Network, national federations), knowledge sharing, advocacy, joint initiatives, and how you learn from peers. Consider participation in EU policy consultations, contributions to the Social Economy Action Plan implementation, and engagement with the EU Social Economy Gateway as a resource and platform.',
        required: true,
        weight: 0,
        placeholder: 'Describe your engagement with European WISE networks (ENSIE, RREUSE, CECOP-CICOPA, Euclid Network) and EU policy processes...',
        tags: ['sector-engagement', 'knowledge-sharing'],
      },
      {
        id: 'stk-q5',
        i18nKey: 'domains.stakeholders.questions.q5.text',
        domainKey: 'stakeholders',
        text: 'Share an example of a partnership — local, national, or European — that has significantly enhanced your social impact.',
        type: 'narrative',
        description: 'Describe a specific partnership, how it developed, and the tangible impact it has had on your participants or mission. This could include transnational cooperation through EU-funded programmes (Horizon Europe, Erasmus+ KA2), participation in ENSIE working groups, or local employer partnerships that have improved social insertion outcomes.',
        required: false,
        weight: 0,
        placeholder: 'Share a partnership success example, including any EU-level or transnational collaborations...',
        tags: ['partnership-impact', 'evidence'],
      },
    ],
  },

  // ─── Domain 7: Support Infrastructure ───
  {
    key: 'support',
    name: 'Support Infrastructure',
    shortName: 'Support',
    description: 'Wrap-around services and accompaniment (accompagnement socioprofessionnel), training provision, mentoring, graduated support, and accessibility — drawing on European approaches to integrated support.',
    icon: 'LifebuoyIcon',
    color: '#F43F5E', // rose
    questions: [
      {
        id: 'sup-q1',
        i18nKey: 'domains.support.questions.q1.text',
        domainKey: 'support',
        text: 'How would you rate the maturity of your support infrastructure, including wrap-around services and socio-professional accompaniment?',
        type: 'maturity',
        description: 'Consider the comprehensiveness of support, accessibility, individualisation, and how support adapts as participants progress. European WISE models offer varied approaches: France\'s accompagnement socioprofessionnel (integrated socio-professional accompaniment), Germany\'s Werkstätten model (structured workshop-based support and transition), and Italy\'s cooperativa sociale Type B (wrap-around cooperative support integrating work and social services).',
        required: true,
        weight: 1.5,
        tags: ['support-services', 'wrap-around'],
      },
      {
        id: 'sup-q2',
        i18nKey: 'domains.support.questions.q2.text',
        domainKey: 'support',
        text: 'To what extent does your organisation provide individualised, graduated accompaniment and support that adapts to participant needs over time?',
        type: 'likert',
        description: '1 = One-size-fits-all approach, 5 = Fully individualised accompaniment plans with graduated intensity, reflecting the French accompagnement socioprofessionnel model. European best practice emphasises that support intensity should reduce progressively as participants build autonomy, while remaining available during and after transition.',
        required: true,
        weight: 1.0,
        tags: ['individualisation', 'graduated-support'],
      },
      {
        id: 'sup-q3',
        i18nKey: 'domains.support.questions.q3.text',
        domainKey: 'support',
        text: 'Describe the range of support services and accompaniment your organisation provides or connects participants to.',
        type: 'narrative',
        description: 'Include in-house services (mentoring, counselling, skills training, socio-professional accompaniment) and external referrals (housing, health, legal, financial). European WISE models emphasise holistic accompaniment: France\'s SIAE structures provide dedicated accompaniment workers (chargés d\'accompagnement); Italian cooperativa sociale Type B integrate social workers within the cooperative; Germany\'s Werkstätten offer structured progression through support levels.',
        required: true,
        weight: 0,
        placeholder: 'Describe your accompaniment and support services, referral networks, and alignment with European integrated support models...',
        tags: ['support-range', 'referrals'],
      },
      {
        id: 'sup-q4',
        i18nKey: 'domains.support.questions.q4.text',
        domainKey: 'support',
        text: 'How do you ensure your services and accompaniment are accessible to diverse participants, including those with complex and multiple barriers?',
        type: 'narrative',
        description: 'Consider physical accessibility, language support, cultural safety, trauma-informed practice, and disability accommodation. The European Charter of Fundamental Rights (Article 26: Integration of persons with disabilities) and the European Accessibility Act establish baseline expectations. European social work traditions emphasise accompaniment that addresses the whole person — not just employment readiness — recognising intersecting barriers of health, housing, language, legal status, and discrimination.',
        required: true,
        weight: 0,
        placeholder: 'Describe your accessibility, inclusion practices, and how accompaniment addresses complex and multiple barriers...',
        tags: ['accessibility', 'complex-needs'],
      },
      {
        id: 'sup-q5',
        i18nKey: 'domains.support.questions.q5.text',
        domainKey: 'support',
        text: 'Share an example of how your support infrastructure and accompaniment made a critical difference for a participant facing complex barriers to social insertion.',
        type: 'narrative',
        description: 'Describe the situation, the accompaniment and supports activated, and the outcome (anonymise personal details). European WISE practice recognises that effective support often requires coordinating multiple services and adapting the accompaniment approach to individual circumstances — illustrate how this worked in practice.',
        required: false,
        weight: 0,
        placeholder: 'Share an anonymised example of effective accompaniment and support for a participant with complex barriers...',
        tags: ['case-study', 'evidence'],
      },
    ],
  },

  // ─── Domain 8: Impact Measurement & Learning ───
  {
    key: 'impact-measurement',
    name: 'Impact Measurement & Learning',
    shortName: 'Impact & Learning',
    description: 'Data collection, outcomes tracking using SROI and Theory of Change methodologies, alignment with ENSIE\'s Impact-WISEs framework and ESEM indicators, and continuous improvement — as promoted by the EU Social Economy Action Plan.',
    icon: 'ChartBarIcon',
    color: '#14B8A6', // teal
    questions: [
      {
        id: 'im-q1',
        i18nKey: 'domains.impactMeasurement.questions.q1.text',
        domainKey: 'impact-measurement',
        text: 'How would you rate the maturity of your impact measurement and organisational learning practices, considering EU frameworks such as ENSIE\'s Impact-WISEs and the European Social Enterprise Monitor (ESEM)?',
        type: 'maturity',
        description: 'Consider data collection systems, outcome frameworks (SROI, Theory of Change), evidence use in decision-making, and continuous improvement processes. The EU Social Economy Action Plan (2021) calls for improved impact measurement across the social economy. ENSIE\'s Impact-WISEs data collection framework provides a standardised approach for comparing WISE outcomes across Europe, and the ESEM indicators offer broader social enterprise benchmarks.',
        required: true,
        weight: 1.5,
        tags: ['measurement', 'learning'],
      },
      {
        id: 'im-q2',
        i18nKey: 'domains.impactMeasurement.questions.q2.text',
        domainKey: 'impact-measurement',
        text: 'How systematically does your organisation collect and use outcome data to improve services, aligned with European impact measurement standards?',
        type: 'likert',
        description: '1 = No systematic data collection, 5 = Comprehensive data system using recognised frameworks (SROI, Theory of Change, ENSIE Impact-WISEs indicators) with regular analysis feeding into service improvement. The EU push for standardised impact measurement in the Social Economy Action Plan aims to enable comparison and learning across WISEs.',
        required: true,
        weight: 1.0,
        tags: ['data-use', 'improvement'],
      },
      {
        id: 'im-q3',
        i18nKey: 'domains.impactMeasurement.questions.q3.text',
        domainKey: 'impact-measurement',
        text: 'Describe your approach to measuring social impact and tracking participant outcomes, including any use of SROI, Theory of Change, or ENSIE\'s Impact-WISEs framework.',
        type: 'narrative',
        description: 'Include tools, frameworks, indicators, frequency of measurement, and how you capture both quantitative and qualitative outcomes. Key European approaches include Social Return on Investment (SROI) for monetising social value, Theory of Change for mapping causal pathways, ENSIE\'s Impact-WISEs data collection framework for standardised WISE indicators, and ESEM (European Social Enterprise Monitor) indicators for broader benchmarking. The EU Social Economy Action Plan encourages adoption of comparable impact measurement methodologies.',
        required: true,
        weight: 0,
        placeholder: 'Describe your impact measurement approach, including use of SROI, Theory of Change, ENSIE Impact-WISEs, or ESEM frameworks...',
        tags: ['measurement-approach', 'outcomes-tracking'],
      },
      {
        id: 'im-q4',
        i18nKey: 'domains.impactMeasurement.questions.q4.text',
        domainKey: 'impact-measurement',
        text: 'How does your organisation use evidence and data to drive continuous improvement, in line with the EU Social Economy Action Plan\'s emphasis on learning organisations?',
        type: 'narrative',
        description: 'Include how data informs strategy, service design, staff development, and stakeholder reporting. The EU Social Economy Action Plan (2021) emphasises that social enterprises should develop robust evidence practices not only for accountability but for organisational learning and sector-wide knowledge building. Consider how your data contributes to broader WISE evidence (e.g., through ENSIE data collection or national observatory reporting).',
        required: true,
        weight: 0,
        placeholder: 'Describe how you use evidence for continuous improvement and contribute to sector-wide learning...',
        tags: ['evidence-use', 'continuous-improvement'],
      },
      {
        id: 'im-q5',
        i18nKey: 'domains.impactMeasurement.questions.q5.text',
        domainKey: 'impact-measurement',
        text: 'Provide an example of how data or evidence — including insights from SROI analysis, Theory of Change review, or ENSIE benchmarking — led to a significant improvement in your services or outcomes.',
        type: 'narrative',
        description: 'Describe what the data showed, what changes were made, and the resulting improvement. The EU push for impact measurement is premised on the belief that robust evidence drives better outcomes — illustrate this with a concrete example from your practice.',
        required: false,
        weight: 0,
        placeholder: 'Share an example of data-driven improvement, referencing the measurement framework or methodology used...',
        tags: ['evidence-impact', 'evidence'],
      },
    ],
  },

  // ─── Domain 9: Environmental Sustainability & Green Transition ───
  {
    key: 'environmental-sustainability',
    name: 'Environmental Sustainability & Green Transition',
    shortName: 'Sustainability',
    description: 'Environmental impact awareness, circular economy practices, green skills development, resource efficiency, and alignment with the EU Green Deal, European Climate Law, and the just transition framework — reflecting the WISESHIFT project\'s focus on WISEs that are inclusive AND sustainable by design.',
    icon: 'GlobeEuropeAfricaIcon',
    color: '#22C55E', // green
    questions: [
      {
        id: 'env-q1',
        i18nKey: 'domains.environmentalSustainability.questions.q1.text',
        domainKey: 'environmental-sustainability',
        text: 'How would you rate the maturity of your organisation\'s environmental sustainability practices, including awareness of the EU Green Deal and circular economy principles?',
        type: 'maturity',
        description: 'Consider whether environmental sustainability is embedded in your strategy, operations, and culture. The EU Green Deal aims for climate neutrality by 2050, and the European Climate Law makes this legally binding. The Circular Economy Action Plan (2020) promotes designing out waste through reuse, repair, and recycling — sectors where many WISEs already operate. The WISESHIFT Horizon Europe project (2025-2029) studies how WISEs can be both socially inclusive and environmentally sustainable.',
        required: true,
        weight: 1.5,
        tags: ['green-transition', 'circular-economy'],
      },
      {
        id: 'env-q2',
        i18nKey: 'domains.environmentalSustainability.questions.q2.text',
        domainKey: 'environmental-sustainability',
        text: 'To what extent does your organisation measure and actively reduce its environmental impact (energy use, waste, emissions, resource consumption)?',
        type: 'likert',
        description: '1 = No environmental measurement or reduction efforts, 5 = Comprehensive environmental monitoring with published targets and demonstrated reductions. The EU Corporate Sustainability Reporting Directive (CSRD) is extending environmental reporting requirements across the economy. While most WISEs are below the CSRD thresholds, adopting basic environmental metrics demonstrates leadership and prepares for evolving expectations. The EU Taxonomy Regulation defines which activities qualify as environmentally sustainable.',
        required: true,
        weight: 1.0,
        tags: ['environmental-impact', 'measurement'],
      },
      {
        id: 'env-q3',
        i18nKey: 'domains.environmentalSustainability.questions.q3.text',
        domainKey: 'environmental-sustainability',
        text: 'Describe how your organisation contributes to the circular economy or environmental sustainability through its productive activities, and how this intersects with your social mission.',
        type: 'narrative',
        description: 'Many WISEs operate in inherently circular sectors: repair, reuse, recycling, upcycling, urban agriculture, green maintenance, and renewable energy installation. Describe how your productive activities contribute to environmental goals while simultaneously providing work integration pathways. Reference the EU Circular Economy Action Plan (2020), the Right to Repair Directive, or the Waste Framework Directive where relevant. The WISESHIFT project specifically studies the intersection of social inclusion and environmental sustainability in WISEs.',
        required: true,
        weight: 0,
        placeholder: 'Describe how your productive activities contribute to circular economy or environmental goals while supporting work integration...',
        tags: ['circular-economy', 'social-environmental'],
      },
      {
        id: 'env-q4',
        i18nKey: 'domains.environmentalSustainability.questions.q4.text',
        domainKey: 'environmental-sustainability',
        text: 'How does your organisation develop green skills and environmental awareness among participants, staff, and the wider community?',
        type: 'narrative',
        description: 'The EU Green Deal emphasises that the green transition must be a just transition — creating opportunities for all, including disadvantaged workers. WISEs are uniquely positioned to develop green skills (energy efficiency, waste management, sustainable agriculture, eco-design) among populations at risk of exclusion. The European Skills Agenda includes green skills as a priority, and ESF+ funding supports green skills development. Describe any green skills training, environmental awareness programmes, or community environmental initiatives your organisation delivers.',
        required: true,
        weight: 0,
        placeholder: 'Describe green skills training, environmental awareness programmes, or community initiatives your organisation provides...',
        tags: ['green-skills', 'just-transition'],
      },
      {
        id: 'env-q5',
        i18nKey: 'domains.environmentalSustainability.questions.q5.text',
        domainKey: 'environmental-sustainability',
        text: 'Share an example of how your organisation has combined environmental sustainability with social inclusion — demonstrating that WISEs can be both green and inclusive by design.',
        type: 'narrative',
        description: 'The WISESHIFT Horizon Europe project is built on the premise that WISEs can simultaneously advance social inclusion and environmental sustainability. Provide a concrete example: a green product or service that creates work integration opportunities, an environmental initiative that engages disadvantaged communities, or a circular economy innovation that addresses both social and environmental challenges. This evidence is particularly valuable for EU policy-makers developing the just transition framework.',
        required: false,
        weight: 0,
        placeholder: 'Share an example of combined environmental and social impact — demonstrating the "inclusive AND sustainable" WISE model...',
        tags: ['dual-impact', 'evidence'],
      },
    ],
  },
];

export const DOMAIN_KEYS = DOMAINS.map(d => d.key);

export function getDomainByKey(key: string): Domain | undefined {
  return DOMAINS.find(d => d.key === key);
}

export function getQuestionById(questionId: string): { domain: Domain; question: Domain['questions'][0] } | undefined {
  for (const domain of DOMAINS) {
    const question = domain.questions.find(q => q.id === questionId);
    if (question) return { domain, question };
  }
  return undefined;
}

export const TOTAL_QUESTIONS = DOMAINS.reduce((sum, d) => sum + d.questions.length, 0);
export const TOTAL_REQUIRED_QUESTIONS = DOMAINS.reduce(
  (sum, d) => sum + d.questions.filter(q => q.required).length, 0
);
