export interface RecommendationTemplate {
  domainKey: string;
  currentLevel: string;
  targetLevel: string;
  recommendation: string;
  description: string;
  effort: 'low' | 'medium' | 'high';
  impact: 'low' | 'medium' | 'high';
  timeframe: 'short' | 'medium' | 'long';
}

export const RECOMMENDATION_TEMPLATES: RecommendationTemplate[] = [
  // ─── Governance & Democracy ───
  {
    domainKey: 'governance',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Establish a formal governance framework aligned with EU social economy principles',
    description: 'Create a documented governance structure with defined roles, meeting schedules, and decision-making protocols, drawing on the EMES democratic governance indicators. Begin with a simple board charter and regular meeting minutes, ensuring alignment with the Council Recommendation on Social Economy Framework Conditions (2023) and the European Pillar of Social Rights principles on worker participation.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'governance',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Diversify board composition and strengthen stakeholder participation using EU cooperative models',
    description: 'Recruit board members from diverse backgrounds including participant representatives, informed by EU social cooperative models such as the Italian social cooperative framework (Law 381/1991) which mandates multi-stakeholder governance. Implement formal consultation mechanisms and feedback loops as promoted by the EU Social Economy Action Plan (2021). Consider ESF+ capacity-building funding to support governance development.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'governance',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Implement participatory governance and transparency measures in line with EU standards',
    description: 'Develop co-governance models with participant voting rights, reflecting the EMES democratic governance indicators and CECOP-CICOPA cooperative governance standards. Publish annual impact reports aligned with the EU Social Economy Action Plan transparency recommendations, and establish independent oversight mechanisms. Use WISESHIFT self-assessment data to benchmark your governance maturity against European peers.',
    effort: 'high',
    impact: 'high',
    timeframe: 'long',
  },
  {
    domainKey: 'governance',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Pioneer democratic governance innovation and contribute to EU social economy policy',
    description: 'Develop and share innovative governance models through CECOP-CICOPA and national social economy networks, mentor other WISEs, and contribute to the implementation of the EU Social Economy Action Plan\'s 38 concrete actions on governance frameworks. Engage with the Council Recommendation on Social Economy Framework Conditions (2023) consultation processes and establish thought leadership through Erasmus+ KA2 Strategic Partnerships for cross-border governance research.',
    effort: 'high',
    impact: 'medium',
    timeframe: 'long',
  },

  // ─── Social Mission & Impact ───
  {
    domainKey: 'social-mission',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Articulate and document your social mission using EU WISE definitions',
    description: 'Develop a clear mission statement aligned with the European Commission\'s definition of work integration social enterprises (WISEs) and the EU Social Economy Action Plan (2021). Identify target populations as referenced in the European Pillar of Social Rights\' 20 principles, and create a basic theory of change linking your activities to intended outcomes using ESEM (European Social Enterprise Monitor) indicators as a guide.',
    effort: 'low',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'social-mission',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Embed mission into operational decisions with EU social economy frameworks',
    description: 'Create mission-alignment criteria for business decisions informed by the European Commission\'s social enterprise definitions and the EMES approach to social enterprise. Develop outcome indicators consistent with ESEM survey categories, and establish regular mission review processes. Reference the EU Social Economy Action Plan\'s emphasis on primacy of social purpose over profit distribution.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'social-mission',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Develop a comprehensive impact evidence base aligned with EU measurement standards',
    description: 'Commission or conduct impact evaluations using recognised EU frameworks such as the ENSIE Impact-WISEs methodology and SROI (Social Return on Investment). Build longitudinal outcome tracking aligned with ESEM indicators, and use evidence to refine mission delivery and attract social investment through the InvestEU social window. Participate in the ESEM survey to benchmark against European peers.',
    effort: 'high',
    impact: 'high',
    timeframe: 'long',
  },
  {
    domainKey: 'social-mission',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Drive systemic social change through EU policy engagement',
    description: 'Use your evidence base to influence the implementation of the EU Social Economy Action Plan\'s 38 concrete actions and the Council Recommendation on Social Economy Framework Conditions (2023). Develop replicable mission models shared via the EU Social Economy Gateway, and contribute to sector-wide social impact measurement standards through ENSIE and the Euclid Network monitoring frameworks.',
    effort: 'high',
    impact: 'high',
    timeframe: 'long',
  },

  // ─── Employment Pathways ───
  {
    domainKey: 'employment',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Design structured employment pathways informed by EU supported employment models',
    description: 'Map progression stages from entry to transition drawing on EU supported employment models, including the French SIAE (Structures d\'Insertion par l\'Activite Economique) pathway approach and the Spanish CEE (Centros Especiales de Empleo) model. Define skill requirements for each stage using B-WISE project digital skills curricula, and create basic individual development plans aligned with the European Pillar of Social Rights principles on employment support.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'employment',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Implement accredited training and transition support using EU frameworks',
    description: 'Partner with training providers for accredited qualifications, integrating B-WISE project resources for digital skills development. Develop transition-to-employment programs informed by the French SIAE stepped pathway model and supported by ESF+ funding for participant training. Track employment outcomes at 6 and 12 months using indicators aligned with ESEM employment pathway metrics.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'employment',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Build employer co-designed employment pathways aligned with EU inclusion standards',
    description: 'Co-design roles with employer partners, implement supported employment models drawing on the EU supported employment framework and the Spanish CEE integrated employment approach. Develop post-placement support to improve retention, and leverage EU social procurement opportunities under Directive 2014/24/EU to create reserved contract employment pathways for disadvantaged workers.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'employment',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Create innovative employment models and influence EU labour market policy',
    description: 'Develop social enterprise spin-offs, create industry-leading transition programs informed by best practice across EU member states, and advocate for inclusive employment policies through ENSIE and national social economy networks. Use Erasmus+ KA2 Strategic Partnerships to share employment pathway innovations and contribute to the EU Social Economy Action Plan implementation on labour market integration.',
    effort: 'high',
    impact: 'high',
    timeframe: 'long',
  },

  // ─── Organisational Culture ───
  {
    domainKey: 'culture',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Establish core values and inclusion policies grounded in EU fundamental rights',
    description: 'Document organisational values rooted in the European Charter of Fundamental Rights\' principles of dignity, equality, and non-discrimination. Create anti-discrimination policies aligned with European social inclusion frameworks, implement basic feedback mechanisms, and provide staff awareness training. Reference the European Pillar of Social Rights\' principles on equal opportunities and active support to employment.',
    effort: 'low',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'culture',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Embed participant voice and trauma-informed practice within EU inclusion frameworks',
    description: 'Create formal participant representation aligned with the European Charter of Fundamental Rights\' right to participation. Adopt trauma-informed frameworks informed by European social inclusion best practice, invest in staff supervision supported by ESF+ capacity-building funding, and implement regular culture surveys using WISESHIFT self-assessment dimensions as a baseline.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'culture',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Co-create an empowerment-centred culture aligned with EU social rights principles',
    description: 'Move from participant consultation to co-creation as envisioned by the European Pillar of Social Rights. Develop peer support programs drawing on European accompagnement socioprofessionnel approaches, implement strength-based methodologies, and build cultural safety practices that reflect the diversity principles of the European Charter of Fundamental Rights.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'culture',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Become a European model of inclusive, empowering organisational culture',
    description: 'Share cultural practices with the sector through ENSIE member networks and the EU Social Economy Gateway. Develop training resources for other WISEs via Erasmus+ KA2 Strategic Partnerships, and contribute to European research on workplace inclusion through Horizon Europe consortia and the B-WISE project knowledge base.',
    effort: 'medium',
    impact: 'medium',
    timeframe: 'long',
  },

  // ─── Economic Sustainability ───
  {
    domainKey: 'economic',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Develop basic financial management and a diversification strategy using EU funding pathways',
    description: 'Implement budgeting processes, identify potential commercial revenue streams, and create a 12-month financial plan. Explore ESF+ and national social economy funds for initial capacity building, and consult the EU Social Economy Gateway for guidance on funding opportunities available to WISEs across EU member states.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'economic',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Strengthen commercial operations and pursue EU social procurement opportunities',
    description: 'Work towards the ENSIE revenue benchmark (European WISEs average 42.8% public funding, 37.6% enterprise revenue, 19.6% private income) by growing commercial revenue. Leverage EU Directive 2014/24/EU on social procurement to access reserved contracts, build 3-month operating reserves, and develop a 3-year business plan that incorporates InvestEU social window readiness.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'economic',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Build financial resilience through diversified EU and market revenue streams',
    description: 'Diversify to 3+ revenue streams including EU social procurement under Directive 2014/24/EU, InvestEU social window instruments, and ESF+ programme funding. Develop social investment readiness for the InvestEU social enterprise guarantee facility, implement scenario planning, and build 6-month reserves. Reference ENSIE revenue data to benchmark your income mix against European peers.',
    effort: 'high',
    impact: 'high',
    timeframe: 'long',
  },
  {
    domainKey: 'economic',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Achieve full financial sustainability and shape EU social finance policy',
    description: 'Reach a self-sustaining financial model, develop innovative financing through the InvestEU social window and national social economy funds. Mentor other WISEs on financial sustainability through ENSIE and the EU Social Economy Gateway, and influence EU social finance policy by contributing to the implementation of the EU Social Economy Action Plan\'s actions on access to finance and markets.',
    effort: 'high',
    impact: 'high',
    timeframe: 'long',
  },

  // ─── Stakeholder Engagement ───
  {
    domainKey: 'stakeholders',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Map stakeholders and connect with EU social economy networks',
    description: 'Conduct stakeholder mapping, establish contact with local employers, and join your national ENSIE member organisation and relevant networks listed on the EU Social Economy Gateway. Create a partnership development plan that includes connections to RREUSE (for reuse/recycling WISEs) or CECOP-CICOPA (for cooperatives) as appropriate to your sector.',
    effort: 'low',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'stakeholders',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Deepen employer partnerships and engage in EU sector networks',
    description: 'Develop formal partnership agreements with 5+ employers, establish regular community engagement activities, and actively participate in ENSIE member organisation activities and EU Social Economy Gateway forums. Join sector-specific networks such as RREUSE or CECOP-CICOPA and engage with the Euclid Network for social enterprise monitoring and peer learning.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'stakeholders',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Build strategic EU alliances and influence social economy policy',
    description: 'Develop strategic partnerships that expand reach across EU member states, engage in policy consultation on the EU Social Economy Action Plan\'s 38 concrete actions, and create collaborative initiatives with peer organisations through Erasmus+ KA2 Strategic Partnerships. Participate in Horizon Europe consortia to strengthen evidence-based advocacy for WISEs.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'stakeholders',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Lead European ecosystem development and cross-border collaboration',
    description: 'Establish and lead multi-stakeholder platforms at the EU level through ENSIE and the EU Social Economy Gateway. Create industry-wide initiatives contributing to the Council Recommendation on Social Economy Framework Conditions (2023), and develop international partnerships via Erasmus+ KA2 Strategic Partnerships and Horizon Europe research programmes to advance the WISE sector across Europe.',
    effort: 'high',
    impact: 'medium',
    timeframe: 'long',
  },

  // ─── Support Infrastructure ───
  {
    domainKey: 'support',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Establish basic support services informed by the European accompagnement socioprofessionnel model',
    description: 'Identify common participant needs, create referral relationships with key services (housing, health, legal) following the European accompagnement socioprofessionnel approach to holistic participant support. Assign dedicated support roles and ensure compliance with EU accessibility standards. Explore ESF+ funding for support infrastructure development.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'support',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Develop individualised support planning using European socioprofessional accompaniment methods',
    description: 'Implement individual support plans rooted in the European accompagnement socioprofessionnel methodology, establish mentoring programmes, provide staff training in support provision using B-WISE project resources, and create graduated support models. Ensure all support services meet EU accessibility standards and align with the European Pillar of Social Rights\' principles on active support to employment.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'support',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Create comprehensive wrap-around support with EU-standard specialist capability',
    description: 'Build in-house specialist support (e.g., counselling, financial literacy) informed by EU best practice models, develop peer support networks drawing on the European accompagnement socioprofessionnel tradition, and implement accessibility audits using EU accessibility standards. Leverage ESF+ and national social economy funds to finance specialist support capacity.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'support',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Pioneer integrated support models and share expertise across Europe',
    description: 'Develop innovative support models building on the European accompagnement socioprofessionnel tradition, create training resources for the sector disseminated via ENSIE and the EU Social Economy Gateway, and contribute to Horizon Europe research on effective support for disadvantaged workers. Share expertise through Erasmus+ KA2 Strategic Partnerships and the WISESHIFT platform.',
    effort: 'high',
    impact: 'medium',
    timeframe: 'long',
  },

  // ─── Impact Measurement & Learning ───
  {
    domainKey: 'impact-measurement',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Establish basic data collection using EU social impact frameworks',
    description: 'Define 3-5 key outcome indicators aligned with the ENSIE Impact-WISEs framework and ESEM survey categories. Implement a simple data collection system informed by the SOCIAL SEEDS evaluation approach, and begin regular reporting on basic metrics. Use WISESHIFT self-assessment as a starting point for structured impact tracking.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'impact-measurement',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Build a comprehensive outcomes framework aligned with European standards',
    description: 'Adopt a recognised outcomes framework such as SROI (Social Return on Investment) methodology or the ENSIE Impact-WISEs framework. Implement regular data analysis and reporting using ESEM indicators, establish feedback loops from data to service improvement, and participate in the ESEM survey to contribute to European-level evidence on WISE impact.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'impact-measurement',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Implement advanced impact evaluation using SROI and EU measurement approaches',
    description: 'Conduct formal impact evaluations using SROI methodology and the SOCIAL SEEDS evaluation approach. Build longitudinal tracking aligned with ENSIE Impact-WISEs indicators, develop data dashboards benchmarked against ESEM survey data, and create a culture of evidence-based decision-making. Participate in the ESEM survey and use the Euclid Network monitoring resources to compare impact across European WISEs.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'impact-measurement',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Lead European sector measurement innovation and evidence building',
    description: 'Contribute to EU sector measurement standards through the ENSIE Impact-WISEs framework and ESEM survey development. Publish impact evidence via the EU Social Economy Gateway, develop innovative measurement approaches building on SROI methodology and the SOCIAL SEEDS evaluation model, and mentor other organisations. Engage in Horizon Europe research programmes to advance impact measurement science for WISEs across Europe.',
    effort: 'high',
    impact: 'medium',
    timeframe: 'long',
  },

  // ─── Environmental Sustainability & Green Transition ───
  {
    domainKey: 'environmental-sustainability',
    currentLevel: 'Emerging',
    targetLevel: 'Developing',
    recommendation: 'Assess your environmental footprint and identify circular economy opportunities',
    description: 'Conduct a basic environmental audit of your operations — energy use, waste streams, water consumption, and transport. Identify where your productive activities already contribute to the circular economy (repair, reuse, recycling) or could be adapted to do so. Consult the EU Circular Economy Action Plan (2020) and the EU Green Deal for frameworks relevant to your sector. Many WISEs already have inherent environmental value that simply needs to be measured and communicated.',
    effort: 'low',
    impact: 'high',
    timeframe: 'short',
  },
  {
    domainKey: 'environmental-sustainability',
    currentLevel: 'Developing',
    targetLevel: 'Established',
    recommendation: 'Integrate environmental targets into strategy and develop green skills training',
    description: 'Set measurable environmental targets (waste reduction, energy efficiency, carbon footprint) and embed them in your organisational strategy alongside social objectives. Develop green skills training for participants — these are increasingly in demand in the labour market and support the EU Just Transition framework. Explore ESF+ and European Climate Facility funding for green skills programmes. Reference the European Skills Agenda\'s emphasis on green skills as a priority.',
    effort: 'medium',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'environmental-sustainability',
    currentLevel: 'Established',
    targetLevel: 'Advanced',
    recommendation: 'Demonstrate dual social-environmental impact with EU-aligned measurement',
    description: 'Develop integrated reporting that demonstrates both social inclusion and environmental sustainability outcomes — the "inclusive AND sustainable" model the WISESHIFT project promotes. Adopt environmental measurement aligned with the EU Taxonomy Regulation criteria where applicable. Pursue eco-certifications relevant to your sector. Participate in RREUSE or relevant green networks to benchmark your environmental performance against European peers.',
    effort: 'high',
    impact: 'high',
    timeframe: 'medium',
  },
  {
    domainKey: 'environmental-sustainability',
    currentLevel: 'Advanced',
    targetLevel: 'Leading',
    recommendation: 'Pioneer the inclusive green transition model and influence EU just transition policy',
    description: 'Position your organisation as a model for how WISEs can drive the green transition while ensuring social inclusion. Contribute to the WISESHIFT Horizon Europe project\'s evidence base on sustainable WISEs. Share innovative practices through ENSIE, RREUSE, and the EU Social Economy Gateway. Engage with EU just transition policy consultations to ensure disadvantaged workers benefit from the green economy. Develop replicable green WISE models through Erasmus+ KA2 partnerships.',
    effort: 'high',
    impact: 'high',
    timeframe: 'long',
  },
];

export function getRecommendationsForDomain(
  domainKey: string,
  currentLevel: string
): RecommendationTemplate[] {
  return RECOMMENDATION_TEMPLATES.filter(
    r => r.domainKey === domainKey && r.currentLevel === currentLevel
  );
}
